# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-28 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
                ('created', models.DateField()),
                ('tag_type', models.BooleanField(choices=[(0, '已完成'), (1, '未完成')], max_length=1)),
            ],
        ),
    ]
