# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-29 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='tag_type',
            field=models.IntegerField(default=0),
        ),
    ]
