# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-22 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20161129_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
    ]
