# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-22 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_todolist_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='add_date',
            field=models.DateTimeField(),
        ),
    ]
