# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-22 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20161222_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='created',
        ),
    ]
