# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-11 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cnword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(blank=True, max_length=255)),
                ('explain', models.TextField()),
                ('py', models.CharField(max_length=255)),
                ('searchcount', models.IntegerField(default=0, verbose_name='查询次数')),
            ],
            options={
                'ordering': ('-searchcount',),
                'db_table': 'cnword',
            },
        ),
    ]
